@echo off
A:\DOS\XMSDSK.EXE 16384 E: /y
A:\DOS\MSCDEX.EXE /D:mscd001 /L:D
A:\DOS\UNZIP.EXE D:\RAMDISK\DOS.ZIP -d E:\ -q
E:\DOS\DOSLFN.COM
E:\DOS\CWSDPMI.EXE
E:\DRIVERS\CTMOUSE.EXE
set PATH=A:\DOS;E:\;E:\DOS;E:\WINDOWS;E:\DRIVERS
CLS
